#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e pulsemixer & ;;
	3) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "Volume \\n" && exit

vol=$(pulsemixer --get-volume | awk '{print $1}')

if [ "$vol" -gt "70" ]; then
	icon="Volume"
elif [ "$vol" -lt "30" ]; then
	icon="Volume"
else
	icon="Volume"
fi

printf "%s %s%%\\n" "$icon" "$vol"
