#!/bin/sh

# Increase key speed via a rate change
xset r rate 300 50
# Map the caps lock key to super
setxkbmap -option caps:super

# But when it is pressed only once, treat it as escape.
killall xcape ; xcape -e 'Super_L=Escape'

# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Super_R'

# turn off keyboard beep
xset b off

# 11/12 this is an experiment to turn screen saver blanking to 1 hour
# I haven't checked to see if it works
# xset s off doesn't work but xset s 60 does seeem to chanking the blanking
# time to 1 minute
xset s 3600
